apiVersion: apps/v1
kind: Deployment
metadata:
 name: client-dep
 labels:
  app: client
spec:
 replicas: 1
 selector:
  matchLabels:
   app: client
 template:
  metadata:
   labels:
    app: client
  spec:
   containers:
    - name: client
      image: kvarc/event_client:latest
      ports:
       - name: client-service
         containerPort: 8081
       
---
apiVersion: v1
kind: Service
metadata:
 name: client-service
spec:
 selector:
  app: client
 ports:
  - port: 8081
    targetPort: client-service

