apiVersion: apps/v1
kind: Deployment
metadata:
 name: server-dep
 labels:
  app: server
spec:
 replicas: 1
 selector:
  matchLabels:
   app: server
 template:
  metadata:
   labels:
    app: server
  spec:
   containers:
    - name: server
      image: kvarc/server-cmd:latest
      ports:
       - name: api-service
         containerPort: 1514
---
apiVersion: v1
kind: Service
metadata:
 name: api-service
spec:
 selector:
  app: server
 ports:
  - protocol: UDP
    port: 1514
    nodePort: 47862
 type: NodePort
